## Redis数据库索引（默认为0）
#spring.redis.database=0
## Redis服务器地址
#spring.redis.host=120.79.208.6
## Redis服务器连接端口
#spring.redis.port=6379
## Redis服务器连接密码（默认为空）
#spring.redis.password=Gxx12345
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active=8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait=-1
## 连接池中的最大空闲连接
#spring.redis.pool.max-idle=8
## 连接池中的最小空闲连接
#spring.redis.pool.min-idle=0
## 连接超时时间（毫秒）
#spring.redis.timeout=0
spring:
  redis:
    database: 0
    #host: 120.79.208.6
    host:127.0.0.1
    port: 6379
    password: Gxx12345
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 9
        min-idle: 0
    timeout:0
