spring:
    profiles: dev
    datasource:
        url:  jdbc:mysql://120.79.208.6:3306/test_spring_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
server:
  port: 8088
mylog:
  path: E:\\work\\learn\\log\\logback.log

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /work/learn/springboot-demo
#  path: /usr/java/project/spring-boot-log
